### PR TITLE
Change colour of link in disclaimer

### PR DESCRIPTION
**Pull request by LucyGwilliamAdmin**

### CODE REVIEW

**Comment by SavvasStephanides** [comment]
Although we're not checking for AAA compliance, it is worth mentioning that it fails the contrast test from WebAIM. It is quite minor, but I think we should try not to introduce new accessibility-related issues, in case we need to comply later on.

image

**Comment by LucyGwilliamAdmin** [comment]
Agree it's worth making sure it's AAA if it's something like this - will change it now :)

**Comment by LucyGwilliamAdmin** [comment]
I have gone with a slightly darker blue which passes AAA:
image

**Comment by SavvasStephanides** [comment]
Excellent. Good job!

**Pull request merged**
