### PR TITLE
Fix for subcategories not appearing in IE.

### PR DESCRIPTION
**Pull request by SavvasStephanides**
The problem is the `.forEach` feature for arrays in `Javascript` is not supported by IE, strangely. Switched to a more "traditional" `for` loop instead.

### CODE REVIEW

**Comment by SavvasStephanides** [comment]
Thanks for testing @LucyGwilliamAdmin. Not sure if this is because I've merged on the `develop` branch instead of `master`. I'll check further 👍

**Comment by LucyGwilliamAdmin** [comment]
@Norric1Admin it still isn't working on IE for me

**Comment by LucyGwilliamAdmin** [comment]
Can you try this on your IE? https://sdg.mango-solutions.com/subcategory-fix/1-2-1/

**Comment by SavvasStephanides** [comment]
@LucyGwilliamAdmin @Norric1Admin I won't be pushing yet. Lucy found it doesn't work in IE so I'm investigating further.

**Comment by dougmet** [comment]
You should be able to test it on the branch build: https://sdg.mango-solutions.com/subcategory-fix/3-2-1/ without need to push to develop (and definitely not master).

**Comment by Norric1Admin** [comment]
Seems to be giving a new error now
image

**Comment by SavvasStephanides** [comment]
Seems like I've left an `i` when I renamed the `for` loop index from `i` to `eachTabIndex`. I think it should work now.

**Comment by LucyGwilliamAdmin** [comment]
It still doesn't seem to be working on internet explorer for me

**Comment by LucyGwilliamAdmin** [comment]
Is this an open-sdg problem?

**Comment by Norric1Admin** [comment]
The problem now is `Object doesn't support property or method 'includes`
A suggested solution is to replace `includes` with `indexOf`. This is purely an IE browser problem :-1: 
https://stackoverflow.com/questions/31119300/using-window-location-hash-includes-throws-object-doesnt-support-property-or

**Comment by Norric1Admin** [comment]
I added a 'polyfill' to `indicator.html` to account for the fact that IE doesn't recognise `includes`.
Categories are now displaying as expected. Long term we'll find a more elegant solution.
https://github.com/ONSdigital/sdg-indicators/commit/21b6ee263b99a9dbb8a5d3691005dbca427edb1a
https://github.com/ONSdigital/sdg-indicators/commit/ba9b854ecb43df6168b27b6082fedc279ebee84c

**Pull request merged**
