### PR TITLE
Open sdg 0.4.0

### PR DESCRIPTION
**Pull request by dougmet**
Upgrades to open-sdg 0.4.0

* Added `goal_image_base` to config for translated goals images
* Upgraded to sdg-translations 0.4.0

Had to copy through overwrites in:
* `reportingstatus.html`
* `indicators.html` 

Got rid of overrides in `goal.html` because we didn't seem to be using it.

Re-added our flag favicons 🇬🇧

Please test on the testing branch before merge

### CODE REVIEW

**Comment by dougmet** [comment]
https://sdg.mango-solutions.com/open-sdg-0-4-0/

**Comment by dougmet** [comment]
Would like to deploy this so need a review @Norric1Admin @LucyGwilliamAdmin

**Comment by Norric1Admin** [comment]
Hi @dougmet thanks for making this. My only question is do we need to edit the head.html (see: https://github.com/open-sdg/open-sdg/pull/117)?
Thanks
Chris

**Comment by dougmet** [comment]
Hi @Norric1Admin thanks for the merge. Yes the [changelog](https://open-sdg.readthedocs.io/en/latest/changelog/#040) didn't mention head.html so no changes were required. I'm working on an [0.5.0 branch](https://github.com/ONSdigital/sdg-indicators/tree/open-sdg-0-5-0), which is building against the open-sdg master branch, so that we can make sure we're ready

**Pull request merged**
