### PR TITLE
Add DAC accreditation logo to FAQ page

### PR DESCRIPTION
**Pull request by SavvasStephanides**
This change will add the DAC logo of which indicates that the site has achieved the AA level for accessibility.

Note: The link to the image temporarily points to the one on the `add-dac-cert` feature branch. This will change as soon as this PR is accepted and the image is present on the master branch.

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
Is there a reason why the logo is above the text in the FAQ question?

**Comment by SavvasStephanides** [comment]
> Is there a reason why the logo is above the text in the FAQ question?

I chose the `accreditation logo --> explanation and details` route

**Comment by LucyGwilliamAdmin** [comment]
Ah ok, personally I think it would look better the other way around

**Comment by SavvasStephanides** [comment]
@LucyGwilliamAdmin We can update it later if we want. Thanks for the review!

**Pull request merged**
