### PR TITLE
Open sdg 0.5.0

### PR DESCRIPTION
**Pull request by dougmet**
Make necessary changes this side to update to open-sdg 0.5.0

* Remove our reporting status override.
* Add CSS for our own status colours
* Goal pages are numbered rather than named (with redirects for old URLs)
* Update configs to include reporting data.
* Updated to use latest open-sdg gems and jekyll redirect

### CODE REVIEW

**Comment by dougmet** [comment]
I think this is ready now.

**Comment by LucyGwilliamAdmin** [comment]
Hi Doug, is there any reason why US's charts expand if there's no disaggregations but ours don't

ours:
image

US's:
image

**Comment by dougmet** [comment]
thanks for the review @LucyGwilliamAdmin is this new? We're probably overriding something. Can I confirm that the only thing we're overriding in indicators.html is the google analytics? If so I'll copy that into a copy of the open-sdg version instead of updating our version.

**Comment by LucyGwilliamAdmin** [comment]
We've also changes line 87 in indicator.html so that we can change the name of the extra tab i.e. we have Chart, Table, Map, Embed but open-sdg has Chart, Table, Map, Map

**Comment by dougmet** [comment]
OK I'll try to gently merge that all together

**Comment by LucyGwilliamAdmin** [comment]
Although it's fine for a different indicator (17.3.2):
image

The first one I posted was 1.1.1

**Comment by LucyGwilliamAdmin** [comment]
Did you want me to review this so that it can be merged?

Chris doesn't work Wednesdays anymore (I don't think anyway)

**Comment by dougmet** [comment]
I'll push a change and request a new review, thanks!

**Comment by dougmet** [comment]
my browser refreshed late, didn't see it was already merged. I'll send in a new PR

**Comment by LucyGwilliamAdmin** [comment]
Hi @dougmet , I'm having a problem with the SDMX columns - Unit measure doesn't seem to be acting in the same way as Observation status and Unit multiplier.

**Comment by LucyGwilliamAdmin** [comment]
Unit measure is showing as a disaggregation while the other two aren't: https://sdg.mango-solutions.com/sdmxcolumns-test/15-7-1/

**Comment by LucyGwilliamAdmin** [comment]
@SavvasStephanides I think it might be something to do with the latest open-sdg repo not being pulled through as the code in the Inspect pane doesn't look as it does in the open-sdg repo..

How can we pull through the latest code?

**Pull request merged**
