### PR TITLE
Create Updates page with placeholder post

### PR DESCRIPTION
**Pull request by SavvasStephanides**
[Test link](https://bit.ly/2BuTI4Q)

This update:

* Creates an Updates page
* Creates a top-level menu called "Updates" which reads the translation from `sdg-translations`*
* Creates an initial placeholder post (see _"The updates page is up!"_)

*The translations JSON URL had to be updated for the latest translation to come through. See `_config.yml` change.

EDIT: please ignore the Netlify messages below. This was something we were trying with James when building the feature branches.

### CODE REVIEW

**Comment by Norric1Admin** [comment]
Looking great! A couple of comments...
- The navigation tabs cluster weirdly if the page size is reduced (think we've reached a maximum).
- Each entry says 'Updates' above it. Could this be replaced with something (e.g. topic tags)?

**Comment by SavvasStephanides** [comment]
> * The navigation tabs cluster weirdly if the page size is reduced (think we've reached a maximum).

I agree. I think that's something we should focus on at a later time.

> * Each entry says 'Updates' above it. Could this be replaced with something (e.g. topic tags)?

Thanks Chris! "Updates" is a topic tag itself so you can add more yourself quite easily as you're creating posts (first few lines of the `.md` file).

**Comment by SavvasStephanides** [comment]
> > * The navigation tabs cluster weirdly if the page size is reduced (think we've reached a maximum).
> 
> I agree. I think that's something we should focus on at a later time.
> 
> > * Each entry says 'Updates' above it. Could this be replaced with something (e.g. topic tags)?
> 
> Thanks @Norric1Admin ! "Updates" is a topic tag itself so you can add more yourself quite easily as you're creating posts (first few lines of the `.md` file).

**Comment by Norric1Admin** [comment]
@SavvasStephanides Nice!

**Comment by SavvasStephanides** [comment]
> What's the netlify fail things though?

@LucyGwilliamAdmin As I mentioned above, it's something James and I have been experimenting with as a way to build feature branches. We'll hopefully remove these soon. It doesn't affect Travis builds or anything else.

**Pull request merged**
