### PR TITLE
Accessibility statement

### PR DESCRIPTION
**Pull request by SavvasStephanides**
The footer will need to be added as an `open-sdg` change somehow.

Test: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/a11y_statement/accessibility-statement/

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
Also how do users get there? Is there going to be link in footer?

**Comment by SavvasStephanides** [comment]
@LucyGwilliamAdmin 

> Page, looks good - could email address at bottom be changed to mailto link though?

Good idea

> Also how do users get there? Is there going to be link in footer?

There's going to be a link in the footer yes. Unfortunately, the change needs to be done in the `open-sdg` repository as there's no `footer.html` file in `sdg-indicators`.

**Comment by LucyGwilliamAdmin** [comment]
As the accessibility statement is something only we have at the moment, it might be worth overwriting footer.html locally

**Comment by AnnCorp** [comment]
We could link it from the FAQ entry, while we're sorting out the footer side of things - I'll do a separate card for this in our Trello.

**Comment by SavvasStephanides** [comment]
@LucyGwilliamAdmin was right. I've overridden the footer to include the statement link. It should now show up on the footer.

**Comment by SavvasStephanides** [comment]
I've also included a link on the FAQ to the statement.

**Pull request merged**
