### PR TITLE
Change text colours in reporting status page

### PR DESCRIPTION
**Pull request by SavvasStephanides**
Updated `default.scss` to show white text for `.status.danger` and `status.notstarted`.

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
I'm looking at this [tool](https://www.sessions.edu/color-calculator/) and it might be helpful to see what colours go well together and then comparing what they would look like with black/white text using this [tool](https://webaim.org/resources/contrastchecker/).

If you enter #38a1c4 in the colour calculator it gives out #c25a38 as a complementary colour - they both pass AA standards with black font (although #c25a38 doesn't pass AAA).

image
image
image

**Comment by LucyGwilliamAdmin** [comment]
Although if we make the colours slightly lighter so #6ea2cc and #c7916a then they both pass AAA standards with black text:

image

image

image

I've also just read this: "If your current contrast ratios are shy of 4.5:1, you’ll need to make some adjustments to meet the AA contrast standard. Keep in mind that adjacent colors aren’t held to the contrast standard. What really matters is contrast between foreground and background, so you won’t have to reskin your entire palette."  so colours next to each other don't matter to AA standards (although we still want to try and be accessible)

@AnnCorp @Norric1Admin what are your thoughts?

**Comment by Norric1Admin** [comment]
Thanks for the suggestions Lucy, but I think you've misunderstood this. Savvas is showing me how to change the text colour so that I can maintain colour contrast against the background and text for two or more colours. This isn't possible with black text only (see [Trello](https://trello.com/c/K0W8dazi/409-update-colours-and-text-in-reporting-status-page) ticket).

**Comment by LucyGwilliamAdmin** [comment]
Oops, sorry - Savvas requested a review so I thought it was going to be merged into the site

**Comment by SavvasStephanides** [comment]
My understanding was that the change of text colour would be merged on to the site which is why I made the pull request. Must’ve misunderstood. Sorry.

**Comment by dougmet** [comment]
Late coming to this (hols). Just wondering where `assets/css/custom.css` went? Seems like the natural home for this sort of override to the defaults.

**Comment by Norric1Admin** [comment]
Hi Doug, hope you enjoyed your hols!
I couldn't get it to work, so have removed it for now. Agree that custom.css is a better approach in future. These changes are working on the reporting status page, but is there a way to make it work on the Goal pages too? https://sdg.mango-solutions.com/colour-test-1/3/

**Pull request closed without merging**
